version: '3.9'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=mongodb://mongo:27017/lms
      - JWT_SECRET=devsecret
      - NODE_ENV=development
      - PORT=5000
      - FRONTEND_URL=http://localhost:5173
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    volumes:
      - ./uploads:/app/uploads
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - VITE_API_BASE_URL=http://localhost:5000
    ports:
      - '5173:5173'
    depends_on:
      - server
volumes:
  mongo_data:
